version: "3"

services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass redispassword1 --port 6379
    container_name: redis_boot
    hostname: redis_boot
    restart: unless-stopped
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
  mysqldb:
    image: mysql:8.0.28
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    # mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql_master
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=password1
      - MYSQL_DATABASES=main
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      # - ./mysql/data:/var/lib/mysql
    networks:
      - db-net
  nodeapp:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: "nodeapp"
    ports:
      - 4000:4000
    networks:
      - db-net
    depends_on:
      - mysqldb
    volumes:
      - ./src:/usr/app/src
    restart: unless-stopped

networks:
  db-net:
