-- MySQL Script generated by MySQL Workbench
-- Sun May 22 03:20:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main` ;
USE `main` ;

-- -----------------------------------------------------
-- Table `main`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`login` (
  `email` VARCHAR(256) NOT NULL,
  `password` VARCHAR(65) NOT NULL,
  `user_id` INT NOT NULL,
  `account_state` INT NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`wallet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `wallet_type` INT NOT NULL,
  `wallet_address` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
